apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-login-deployment
  labels:
    app: spring-login
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-login
  template:
    metadata:
      labels:
        app: spring-login
    spec:
      containers:
        - name: task4login
          image: gcr.io/gcp-docker-kubernetes-1561997/task4login:1.0
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: spring-login-config
                  key: MYSQL_DB_HOST
            - name: MYSQL_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: spring-login-config
                  key: MYSQL_DB_USER
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: spring-login-config
                  key: MYSQL_DB_PASSWORD
            - name: MYSQL_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: spring-login-config
                  key: MYSQL_DB_PORT
            - name: CHAT_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: spring-login-config
                  key: CHAT_ENDPOINT
