apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-profile-deployment
  labels:
    app: spring-profile
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-profile
  template:
    metadata:
      labels:
        app: spring-profile
    spec:
      containers:
        - name: task5profile
          image: acrp2task5.azurecr.io/task5profile:1.0
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: spring-profile-config
                  key: MYSQL_DB_HOST
            - name: MYSQL_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: spring-profile-config
                  key: MYSQL_DB_USER
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: spring-profile-config
                  key: MYSQL_DB_PASSWORD
            - name: MYSQL_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: spring-profile-config
                  key: MYSQL_DB_PORT
          resources:
            requests:
              cpu: 200m
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: azure-php-apache-profile
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spring-profile-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 83